FINANCIAL_MODELLING_PREP_API = "https://financialmodelingprep.com/api/v3"
STOCK_MARKET_CLOUD_STORAGE_BUCKET = "stock-market-research-tf-state-stock-market-research"

COMPANY_PROFILE_ENDPOINT = FINANCIAL_MODELLING_PREP_API + "/profile"
INCOME_STATEMENT_ENDPOINT = FINANCIAL_MODELLING_PREP_API + "/income-statement"
BALANCE_SHEET_STATEMENT_ENDPOINT = FINANCIAL_MODELLING_PREP_API + "/balance-sheet-statement"
CASH_FLOW_STATEMENT_ENDPOINT = FINANCIAL_MODELLING_PREP_API + "/cash-flow-statement"

LOCAL_STATEMENT_TYPE_TO_ENDPOINT_MAPPING = {
    "income_statement": INCOME_STATEMENT_ENDPOINT,
    "balance_sheet_statement": BALANCE_SHEET_STATEMENT_ENDPOINT,
    "cash_flow_statement": CASH_FLOW_STATEMENT_ENDPOINT
}


REQUEST_ATTEMPTS_BEFORE_FAIL = 200
