name: Terraform plan

on:
  pull_request:
    paths:
      - 'terraform/modules/stock_market_research/**'
    secrets:
      STOCK_MARKET_RESEARCH_DB_USER_PASSWORD:
        required: true
      WORKLOAD_IDENTITY_PROVIDER:
        required: true
      TERRAFORM_SERVICE_ACCOUNT:
        required: true
      FINANCIAL_MODELING_PREP_API_TOKEN:
        required: true
  push:
    branches:
      - main
    paths:
      - 'terraform/modules/stock_market_research/**'
    secrets:
      STOCK_MARKET_RESEARCH_DB_USER_PASSWORD:
        required: true
      WORKLOAD_IDENTITY_PROVIDER:
        required: true
      TERRAFORM_SERVICE_ACCOUNT:
        required: true
      FINANCIAL_MODELING_PREP_API_TOKEN:
        required: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  pull-requests: write

jobs:
  generate-plan:
    runs-on: ubuntu-latest
    environment: terraform-plan
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        id: authenticate_with_gcp
        uses: google-github-actions/auth@v0.8.1
        with:
          service_account: ${{ secrets.TERRAFORM_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Set up GCP SDK
        id: set_up_gcp_sdk
        uses: google-github-actions/setup-gcloud@v0.6.0

      - name: Install Terraform
        id: install_terraform
        uses: hashicorp/setup-Terraform@v1
        with:
          terraform_version: 1.8.4
          terraform_wrapper: true

      - name: Confirm Terraform version
        id: confirm_terraform_version
        run: |
          terraform --version
          which terraform

      - name: Terraform validate
        id: terraform_validate
        run: |
          cd terraform/modules/stock_market_research
          terraform init
          terraform validate
        env:
          TF_VAR_stock_market_research_db_user_password: ${{ secrets.STOCK_MARKET_RESEARCH_DB_USER_PASSWORD }}
          TF_VAR_financial_modeling_prep_api_token: ${{ secrets.FINANCIAL_MODELING_PREP_API_TOKEN }}

      - name: Terraform plan and copy to GCS
        id: terraform_plan_and_copy_to_gcs
        run: |
          cd terraform/modules/stock_market_research
          terraform plan
        env:
          TF_VAR_stock_market_research_db_user_password: ${{ secrets.STOCK_MARKET_RESEARCH_DB_USER_PASSWORD }}
          TF_VAR_financial_modeling_prep_api_token: ${{ secrets.FINANCIAL_MODELING_PREP_API_TOKEN }}

  apply-plan:
    runs-on: ubuntu-latest
    environment: terraform-apply
    needs: [generate-plan]
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        id: authenticate_with_gcp
        uses: google-github-actions/auth@v0.8.1
        with:
          service_account: ${{ secrets.TERRAFORM_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Set up GCP SDK
        id: set_up_gcp_sdk
        uses: google-github-actions/setup-gcloud@v0.6.0

      - name: Install Terraform
        id: install_terraform
        uses: hashicorp/setup-Terraform@v1
        with:
          terraform_version: 1.8.4
          terraform_wrapper: true

      - name: Confirm Terraform version
        id: confirm_terraform_version
        run: |
          terraform --version
          which terraform

      - name: Terraform apply
        id: terraform_apply
        run: |
          cd terraform/modules/stock_market_research
          terraform init
          terraform apply --auto-approve
        env:
          TF_VAR_stock_market_research_db_user_password: ${{ secrets.STOCK_MARKET_RESEARCH_DB_USER_PASSWORD }}
          TF_VAR_financial_modeling_prep_api_token: ${{ secrets.FINANCIAL_MODELING_PREP_API_TOKEN }}
