name: Terraform plan

on:
  pull_request:
    paths:
      - 'terraform/modules/**'
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  pull-requests: write

jobs:
  generate-plan:
    runs-on: ubuntu-latest
    environment: terraform-plan
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        id: authenticate_with_gcp
        uses: google-github-actions/auth@v0.8.1
        with:
          service_account: 'service-terraform@stock-market-research-410417.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/824941781846/locations/global/workloadIdentityPools/terraform-pool/providers/terraform-provider'

      - name: Set up GCP SDK
        id: set_up_gcp_sdk
        uses: google-github-actions/setup-gcloud@v0.6.0

      - name: Install Terraform
        id: install_terraform
        uses: hashicorp/setup-Terraform@v1
        with:
          terraform_version: 1.3.7
          terraform_wrapper: true

      - name: Confirm Terraform version
        id: confirm_terraform_version
        run: |
          terraform --version
          which terraform

      - name: Terraform validate
        id: terraform_validate
        run: |
          cd terraform/modules/stock_market_research
          terraform init
          terraform validate

      - name: Terraform plan and copy to GCS
        id: terraform_plan_and_copy_to_gcs
        run: |
          cd terraform/modules/stock_market_research
          terraform plan -out=/tmp/tf.plan -no-color
          gsutil cp /tmp/tf.plan gs://stock-market-research-tf-state-stock-market-research/terraform/europe-north1/stock_market_research/terraform.tfstate/tf.plan
          echo "Terraform plan copied to gs://stock-market-research-tf-state-stock-market-research/terraform/europe-north1/stock_market_research/terraform.tfstate/tf.plan"

      - name: Comment PR
        id: comment_pr
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "${{ steps.terraform_plan_and_copy_to_gcs.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Plan 📖\`${{ steps.terra_plan.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.terra_validate.outcome }}\`

            <details><summary>Show Plan (${{ inputs.env_name }})</summary>

            \`\`\`terraform\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

  apply-plan:
    runs-on: ubuntu-latest
    environment: terraform-apply
    needs: [terraform-plan]
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        id: authenticate_with_gcp
        uses: google-github-actions/auth@v0.8.1
        with:
          service_account: 'service-terraform@stock-market-research-410417.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/824941781846/locations/global/workloadIdentityPools/terraform-pool/providers/terraform-provider'

      - name: Set up GCP SDK
        id: set_up_gcp_sdk
        uses: google-github-actions/setup-gcloud@v0.6.0

      - name: Install Terraform
        id: install_terraform
        uses: hashicorp/setup-Terraform@v1
        with:
          terraform_version: 1.3.7
          terraform_wrapper: true

      - name: Confirm Terraform version
        id: confirm_terraform_version
        run: |
          terraform --version
          which terraform

      - name: Terraform apply
        id: terraform_apply
        run: |
          gsutil cp gs://stock-market-research-tf-state-stock-market-research/terraform/europe-north1/stock_market_research/terraform.tfstate/tf.plan /tmp/tf.plan
          cd terraform/modules/stock_market_research
          terraform apply -input=false /tmp/tf.plan -no-color

      - name: Remove applied plan from GCS
        id: remove_applied_plan
        run: |
          gsutil rm gs://stock-market-research-tf-state-stock-market-research/terraform/europe-north1/stock_market_research/terraform.tfstate/tf.plan
