name: Run pytest

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
      dependencies_path:
        required: true
        type: string

permissions:
  contents: read
  id-token: write
  pull-requests: write


jobs:
  run-tests:
    name: Run python tests
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: setup_python
        name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - id: install_requirements
        run: |
          pip install -r ${{ inputs.dependencies_path }}
      
      - id: execute_pytest
        run: |
          pytest
